### ISSUE TITLE
When providing Client tls configuration to the custom resources, the operator doesn't actually use the provided secret/configmaps

### ISSUE THREAD

**Issue by dougkirkley** [perses/perses-operator#125]
The operator only looks at the path fields even if it isn't a file type.

Using the the Perses resource below, I expect that the operator would handle retrieving the certificate data from the provided `client.tls` configuration.

```
apiVersion: perses.dev/v1alpha1
kind: Perses
metadata:
  labels:
    app.kubernetes.io/name: perses
    app.kubernetes.io/part-of: perses-operator
    app.kubernetes.io/created-by: perses-operator
  name: perses
spec:
  client:
    tls:
      enable: true
      userCert:
        type: secret
        name: perses-cert
        certPath: tls.crt
        privateKeyPath: tls.key
      caCert:
        type: configmap
        name: ca-bundle
        certPath: ca.crt
  tls:
    enable: true
    userCert:
      type: secret
      name: perses-cert
      certPath: tls.crt
      privateKeyPath: tls.key
    caCert:
      type: configmap
      name: ca-bundle
      certPath: ca.crt
  config:
    database:
      file:
        folder: "/etc/perses/storage"
        extension: "yaml"
    ephemeral_dashboard:
      enable: false
      cleanup_interval: "1s"

  containerPort: 8443
  storage:
    size: 10Gi
```

Result the operator says it can't find the certificate file locally because the operator doesn't retrieve the data provided and only checks the file path.
