### ISSUE TITLE
`model.Duration` Serialization Incompatibility with Kubernetes API

### ISSUE THREAD

**Issue by ibakshay** [perses/perses-operator#20]
While working  on [updating the dependencies and go version](https://github.com/perses/perses-operator/issues/16) on my fork and encountered an issue with the serialization of `model.Duration` in the Perses CRD.

Some of the Perses CRD spec fields such as `spec.config.ephemeral_dashboard.cleanup_interval`, `spec.config.provisioning.interval` uses `model.Duration` from [prometheus/common/time.go](https://github.com/prometheus/common/blob/653e0fa37b474f7af331bbfb409c0f654fb04a94/model/time.go).

prometheus/common/time.go [has a custom JSON serialisation](https://github.com/prometheus/common/blob/653e0fa37b474f7af331bbfb409c0f654fb04a94/model/time.go#L120-L122) that converts implicitly to `type:string`. This conflicts with the Kubernetes API's expectation of a `type: integer` instead. This mismatch prevents the [perses_controller](https://github.com/perses/perses-operator/blob/main/controllers/perses/perses_controller.go#L139-L141) from updating Perses resources, resulting in validation errors like:

```
Perses.perses.dev "perses-sample" is invalid: spec.config.ephemeral_dashboard.cleanup_interval: Invalid value: "string": spec.config.ephemeral_dashboard.cleanup_interval in body must be of type integer: "string"
```

This occurs because the [prometheus/common](https://github.com/prometheus/common/blob/653e0fa37b474f7af331bbfb409c0f654fb04a94/model/time.go#L120-L121)`package marshals `model.Duration` to a string:

```go
// MarshalJSON implements the json.Marshaler interface.
func (d Duration) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.String())
}
```

### Perses CRD definition (config/crd/bases/perses.dev_perses.yaml)

```yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: perses.perses.dev
spec:
  # ... (other parts of the CRD)

  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Perses is the Schema for the perses API
        properties:
          # ... (other properties)
          spec:
            description: PersesSpec defines the desired state of Perses
            properties:
              config:
                properties:
                  # ... (other properties)
                  ephemeral_dashboard:
                    description: EphemeralDashboard contains the config about the ephemeral dashboard feature
                    properties:
                      cleanup_interval:
                        description: The interval at which to trigger the cleanup of ephemeral dashboards, based on their TTLs.
                        format: int64  # This indicates that Kubernetes expects an integer
                        type: integer
                      # ... (other properties)
                  # ... (other properties that use model.Duration)
            # ... (rest of the schema)
```
As seen in the CRD definition, `spec.config.ephemeral_dashboard.cleanup_interval` is explicitly defined as an integer (`format: int64`, `type: integer`) showing the incompatibility. This issue needs to be addressed to ensure compatibility of the Perses controller for managing the time duration fields of the Perses Config .

**Comment by frezes** [comment]
There is a workaround method, use patch to modify the crd field:  https://github.com/perses/perses-operator/compare/main...frezes:perses-operator:develop#diff-2c2b2008b7840f3d21a3262975c4aff6ba1e5f89f394ed344a512beb53525c84R1

**Comment by ibakshay** [comment]
Hi @Nexucis, @jgbernalp, 
When using `model.Duration` from prometheus/common in CRD properties, kubebuilder annotations for type validation are not being respected during CRD generation. The generated CRD shows the type as `integer` despite explicitly marking it as `string` with kubebuilder annotations.

### Current Implementation
```go
// I/O read timeout
// +kubebuilder:validation:Type=string
// +kubebuilder:validation:Format=duration
ReadTimeout model.Duration `json:"read_timeout" yaml:"read_timeout"`
```

### Current Behavior
Running `make manifests` generates a CRD with:
```yaml
read_timeout:
  allOf:
  - format: int64
  - format: duration
  description: I/O read timeout
  type: integer
```

### Expected Behavior
The generated CRD should respect the kubebuilder annotations and output:
```yaml
read_timeout:
  description: I/O read timeout
  type: string
  format: duration
```

### Error Output
```
github.com/perses/perses-operator/api/v1alpha1:-: conflicting types in allOf branches in schema: integer vs string
Error: not all generators ran successfully
```

### Investigation Details
1. The error suggests a type conflict in the OpenAPI schema generation
2. Despite using `+kubebuilder:validation:Type=string`, controller-gen seems to detect the underlying type of `model.Duration` (which is an int64)
3. The `allOf` section in the generated CRD indicates that multiple type definitions are being merged incorrectly

### Additional Context
This issue affects any properties in our CRDs that use `model.Duration`.

Do you know what I am missing maybe? @jgbernalp
